### ISSUE TITLE
Entitlements problem ?

### ISSUE THREAD

**Issue by gavineadie** [twostraws/Brisk#1]
`let html = String(url: "https://www.swift.org")`

BriskScript[11096:401899] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=11096

**Comment by twostraws** [comment]
Are you saying it doesn’t fetch the string, or just that it prints something in Xcode’s log?

**Comment by gavineadie** [comment]
It just prints that in the Xcode log .. the only other line in the script is the import of Foundation.

**Comment by twostraws** [comment]
Right, so maybe try printing the string you got back? I would imagine the Xcode output isn’t important.

**Comment by gavineadie** [comment]
The string does print correctly.

**Comment by twostraws** [comment]
Great! So it’s all OK.
